### PR TITLE
Add scroll-spy-active and scroll-spy-link directives

### PR DESCRIPTION
**Pull request by Toilal**
Many changes that I hope will be merged and released as a new major version :)

This allow to handle menu active class and links easily with new directives, making data binding really optional in most cases.

It also add supports for multiple scroll-spy directives in the same app with data-scroll-spy-id, and set the value to last index when scroll is at bottom.

Dependencies have been upgraded, ESLint added, webpack configuration enhanced.

### CODE REVIEW

**Comment by ibufu** [comment]
Awesome! I will spend time to review these changes later. Thank you! :)

**Comment by Toilal** [comment]
when you merge this, it may cause issue with github pages because index.html in now generated in /docs/dist... I could update the configuration by creating a docs-src directory with docs sources, and set dist directory to /docs

**Comment by Toilal** [comment]
I have fixed many issues, it should run fine now.

**Comment by ibufu** [comment]
Are there two usages ?
```
v-scroll-spy="section"   
```
```
v-scroll-spy="{data: section}"
```

**Comment by Toilal** [comment]
It's a mistake in demo.vue, I just pushed again changes. The usage is now `v-scroll-spy="{data: 'section'}"` if you need to bind the section index to a data property.

**Comment by ibufu** [comment]
@Toilal , The demo still doesn't work well. Could you help to fix it? I would like to add some new features later. Then, release it as v2.

**Comment by Toilal** [comment]
I fixed the issue in demo with section index staying to 0.

**Comment by ibufu** [comment]
Thanks!

**Pull request merged**
